import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import { db, id, labelsToColumn, now, hash, passwordHash, passwordMatches, createToken, userFromToken, userFromApiKey, publicTask, publicUser, saveSettings, settingsFor, taskForUser } from './db.mjs'
import { mergeSettings, providerStatus, publicSettings, resolveProviderConfig } from './settings.mjs'
import { checkSignup, clientIp, createRateLimiter } from './security.mjs'
import { aiBreakdown, aiEstimate, createTasksFromRamble, transcribeGroq } from './providers.mjs'
import { buildSchedule } from './domain.mjs'

const app = express()
const port = Number(process.env.PORT || 8787)
const signupCode = String(process.env.SIGNUP_CODE || '').trim()
// Provider credentials resolve per request: workspace settings win over server env.
const providerConfig = req => resolveProviderConfig(settingsFor(req.user.id), process.env)
const registerLimiter = createRateLimiter({ windowMs: 60 * 60 * 1000, max: Number(process.env.REGISTER_LIMIT_PER_HOUR || 5) })
const loginLimiter = createRateLimiter({ windowMs: 15 * 60 * 1000, max: Number(process.env.LOGIN_LIMIT_PER_15_MIN || 20) })
app.set('trust proxy', 1)
app.use(cors({ origin: process.env.CORS_ORIGIN?.split(',') || true, credentials: true }))
app.use(express.json({ limit: '15mb' }))
app.use((req, _res, next) => { req.requestId = id(); next() })
const readBearer = req => req.headers.authorization?.startsWith('Bearer ') ? req.headers.authorization.slice(7) : null
function auth(req, res, next) { const bearer = readBearer(req); const user = userFromToken(bearer) || userFromApiKey(bearer) || userFromApiKey(req.headers['x-tadoo-api-key']); if (!user) return res.status(401).json({ error: 'Authentication required' }); req.user = user; next() }
function rateLimited(res, limit) { if (limit.allowed) return false; res.set('Retry-After', String(limit.retryAfterSeconds)); return true }
const taskPayload = body => ({ title: String(body.title || '').trim(), project: String(body.project || 'Inbox').trim() || 'Inbox', priority: Math.min(3, Math.max(1, Number(body.priority || 2))), durationMinutes: Math.min(180, Math.max(5, Number(body.durationMinutes || 15))), dueDate: body.dueDate || null, notes: String(body.notes || ''), parentId: body.parentId || null, labels: labelsToColumn(body.labels) })

app.get('/api/health', (_req, res) => res.json({ ok: true, service: 'tadoo-api', time: now() }))
app.get('/api/auth/config', (_req, res) => res.json({ signupCodeRequired: Boolean(signupCode) }))
app.post('/api/auth/register', (req, res) => {
  if (rateLimited(res, registerLimiter(clientIp(req)))) return res.status(429).json({ error: 'Too many sign-up attempts. Please try again later.' })
  const problem = checkSignup(req.body || {}, signupCode)
  if (problem) return res.status(problem.status).json({ error: problem.error })
  const { email, password } = req.body
  try { const user = { id: id(), email: email.toLowerCase(), password_hash: passwordHash(password), created_at: now() }; db.prepare('INSERT INTO users VALUES (@id,@email,@password_hash,@created_at)').run(user); const token = createToken(); db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(hash(token), user.id, new Date(Date.now() + 1000 * 60 * 60 * 24 * 30).toISOString()); res.status(201).json({ token, user: publicUser(user) }) } catch (error) { res.status(error.code === 'SQLITE_CONSTRAINT_UNIQUE' ? 409 : 500).json({ error: error.code === 'SQLITE_CONSTRAINT_UNIQUE' ? 'Email already registered' : 'Could not create account' }) } })
app.post('/api/auth/login', (req, res) => {
  if (rateLimited(res, loginLimiter(clientIp(req)))) return res.status(429).json({ error: 'Too many sign-in attempts. Please try again later.' })
  const { email, password } = req.body || {}; const user = db.prepare('SELECT * FROM users WHERE email=?').get(String(email || '').toLowerCase()); if (!user || !passwordMatches(String(password || ''), user.password_hash)) return res.status(401).json({ error: 'Invalid email or password' }); const token = createToken(); db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(hash(token), user.id, new Date(Date.now() + 1000 * 60 * 60 * 24 * 30).toISOString()); res.json({ token, user: publicUser(user) }) })
app.post('/api/auth/logout', auth, (req, res) => { const token = readBearer(req); if (token) db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(token)); res.status(204).end() })
app.get('/api/auth/me', auth, (req, res) => res.json({ user: publicUser(req.user) }))
app.post('/api/auth/api-key', auth, (req, res) => { const token = createToken('tdk_'); db.prepare('INSERT INTO api_keys VALUES (?,?,?,?,?)').run(id(), req.user.id, String(req.body?.name || 'Hermes agent'), hash(token), now()); res.status(201).json({ key: token, warning: 'Store this key securely. It will not be shown again.' }) })

app.get('/api/tasks', auth, (req, res) => { const rows = db.prepare('SELECT * FROM tasks WHERE user_id=? ORDER BY completed ASC, CASE WHEN due_date IS NULL THEN 1 ELSE 0 END, due_date ASC, priority ASC, created_at DESC').all(req.user.id); res.json({ tasks: rows.map(publicTask) }) })
app.post('/api/tasks', auth, (req, res) => { const p = taskPayload(req.body || {}); if (!p.title) return res.status(400).json({ error: 'title is required' }); const row = { id: id(), user_id: req.user.id, title: p.title, project: p.project, priority: p.priority, duration_minutes: p.durationMinutes, due_date: p.dueDate, completed: 0, notes: p.notes, parent_id: p.parentId, labels: p.labels, created_at: now(), updated_at: now() }; db.prepare('INSERT INTO tasks (id,user_id,title,project,priority,duration_minutes,due_date,completed,notes,parent_id,labels,created_at,updated_at) VALUES (@id,@user_id,@title,@project,@priority,@duration_minutes,@due_date,@completed,@notes,@parent_id,@labels,@created_at,@updated_at)').run(row); res.status(201).json({ task: publicTask(row) }) })
app.patch('/api/tasks/:id', auth, (req, res) => { const existing = taskForUser(req.user.id, req.params.id); if (!existing) return res.status(404).json({ error: 'Task not found' }); const p = taskPayload({ ...existing, ...req.body }); const completed = req.body.completed === undefined ? existing.completed : Boolean(req.body.completed); db.prepare('UPDATE tasks SET title=?,project=?,priority=?,duration_minutes=?,due_date=?,completed=?,notes=?,parent_id=?,labels=?,updated_at=? WHERE id=? AND user_id=?').run(p.title,p.project,p.priority,p.durationMinutes,p.dueDate,completed ? 1 : 0,p.notes,p.parentId,p.labels,now(),req.params.id,req.user.id); res.json({ task: taskForUser(req.user.id, req.params.id) }) })
app.delete('/api/tasks/:id', auth, (req, res) => { const result = db.prepare('DELETE FROM tasks WHERE id=? AND user_id=?').run(req.params.id, req.user.id); if (!result.changes) return res.status(404).json({ error: 'Task not found' }); res.status(204).end() })
app.post('/api/tasks/:id/breakdown', auth, async (req, res) => { const task = taskForUser(req.user.id, req.params.id); if (!task) return res.status(404).json({ error: 'Task not found' }); const items = await aiBreakdown(req.user, task, providerConfig(req)); res.json({ taskId: task.id, items, provider: providerConfig(req).opencode.apiKey ? 'opencode-go' : 'local-fallback' }) })
app.post('/api/tasks/:id/estimate', auth, async (req, res) => { const task = taskForUser(req.user.id, req.params.id); if (!task) return res.status(404).json({ error: 'Task not found' }); const minutes = await aiEstimate(req.user, task, providerConfig(req)); db.prepare('UPDATE tasks SET duration_minutes=?,updated_at=? WHERE id=?').run(minutes, now(), task.id); res.json({ task: taskForUser(req.user.id, task.id), provider: providerConfig(req).opencode.apiKey ? 'opencode-go' : 'local-fallback' }) })

app.post('/api/ramble/preview', auth, async (req, res) => { try { let text = String(req.body?.text || '').trim(); if (!text && req.body?.audioBase64) text = await transcribeGroq(req.body.audioBase64, req.body.mimeType, providerConfig(req).groq) || ''; if (!text) return res.status(400).json({ error: 'text or audioBase64 is required' }); const tasks = await createTasksFromRamble(req.user, text, providerConfig(req)); const preview = tasks.map(input => ({ id: id(), title: String(input.title || text).trim(), project: input.project || 'Inbox', priority: Number(input.priority || 2), durationMinutes: Number(input.durationMinutes || 15), dueDate: input.dueDate || null, completed: false, notes: input.notes || '', parentId: input.parentId || null, labels: labelsToColumn(input.labels), createdAt: now(), updatedAt: now() })); res.json({ transcript: text, tasks: preview, provider: providerConfig(req).groq.apiKey ? 'groq-whisper' : 'text-input' }) } catch (error) { res.status(502).json({ error: 'Ramble preview failed', detail: error.message }) } })

app.post('/api/ramble', auth, async (req, res) => { try { let text = String(req.body?.text || '').trim(); if (!text && req.body?.audioBase64) text = await transcribeGroq(req.body.audioBase64, req.body.mimeType, providerConfig(req).groq) || ''; if (!text) return res.status(400).json({ error: 'text or audioBase64 is required' }); const tasks = await createTasksFromRamble(req.user, text, providerConfig(req)); const created = tasks.map(input => { const p = taskPayload(input); const row = { id:id(), user_id:req.user.id, title:p.title || text, project:p.project, priority:p.priority, duration_minutes:p.durationMinutes, due_date:p.dueDate, completed:0, notes:p.notes, parent_id:p.parentId, labels:p.labels, created_at:now(), updated_at:now() }; db.prepare('INSERT INTO tasks (id,user_id,title,project,priority,duration_minutes,due_date,completed,notes,parent_id,labels,created_at,updated_at) VALUES (@id,@user_id,@title,@project,@priority,@duration_minutes,@due_date,@completed,@notes,@parent_id,@labels,@created_at,@updated_at)').run(row); return publicTask(row) }); res.status(201).json({ transcript: text, tasks: created, provider: providerConfig(req).groq.apiKey ? 'groq-whisper' : 'text-input' }) } catch (error) { res.status(502).json({ error: 'Ramble processing failed', detail: error.message }) } })

app.get('/api/reminders', auth, (req, res) => { const rows = db.prepare('SELECT r.*, t.title FROM reminders r JOIN tasks t ON t.id=r.task_id WHERE r.user_id=? ORDER BY r.remind_at ASC').all(req.user.id); res.json({ reminders: rows }) })
app.post('/api/tasks/:id/reminders', auth, (req, res) => { const task = taskForUser(req.user.id, req.params.id); const parsedDate = Date.parse(req.body?.remindAt || ''); if (!task || Number.isNaN(parsedDate)) return res.status(400).json({ error: 'Valid task and remindAt are required' }); const remindAt = new Date(parsedDate).toISOString(); const reminder = { id:id(), task_id:task.id, user_id:req.user.id, remind_at:remindAt }; db.prepare('INSERT INTO reminders (id,task_id,user_id,remind_at) VALUES (@id,@task_id,@user_id,@remind_at)').run(reminder); res.status(201).json({ reminder: { ...reminder, taskTitle: task.title } }) })
app.delete('/api/reminders/:id', auth, (req, res) => { const result = db.prepare('DELETE FROM reminders WHERE id=? AND user_id=?').run(req.params.id, req.user.id); if (!result.changes) return res.status(404).json({ error: 'Reminder not found' }); res.status(204).end() })

app.get('/api/schedule/day', auth, (req, res) => { const tasks = db.prepare('SELECT * FROM tasks WHERE user_id=? AND completed=0 ORDER BY priority ASC').all(req.user.id).map(row => ({ id: row.id, title: row.title, durationMinutes: row.duration_minutes, priority: row.priority })); const focusBlocks = req.body?.focusBlocks || [{ start: String(req.query.start || '09:00'), end: String(req.query.end || '12:00') }, { start: '13:00', end: '17:00' }]; res.json({ date: req.query.date || new Date().toISOString().slice(0,10), plan: buildSchedule(tasks, focusBlocks), provider: 'local-scheduler' }) })
app.post('/api/schedule/replan', auth, (req, res) => { const tasks = db.prepare('SELECT * FROM tasks WHERE user_id=? AND completed=0').all(req.user.id).map(row => ({ id: row.id, title: row.title, durationMinutes: row.duration_minutes, priority: row.priority })); const focusBlocks = req.body?.focusBlocks || [{ start: '09:00', end: '12:00' }, { start: '13:00', end: '17:00' }]; res.json({ plan: buildSchedule(tasks, focusBlocks), replannedAt: now(), reason: req.body?.reason || 'schedule refreshed' }) })

app.get('/api/settings', auth, (req, res) => { const stored = settingsFor(req.user.id); res.json({ settings: publicSettings(stored), providers: providerStatus(stored, process.env) }) })
app.put('/api/settings', auth, (req, res) => { const stored = mergeSettings(settingsFor(req.user.id), req.body || {}); saveSettings(req.user.id, stored); res.json({ settings: publicSettings(stored), providers: providerStatus(stored, process.env) }) })

app.get('/api/keys', auth, (req, res) => { res.json({ keys: db.prepare('SELECT id, name, created_at FROM api_keys WHERE user_id=? ORDER BY created_at DESC').all(req.user.id).map(row => ({ id: row.id, name: row.name, createdAt: row.created_at })) }) })
app.post('/api/keys', auth, (req, res) => { const token = createToken('tdk_'); const keyId = id(); db.prepare('INSERT INTO api_keys VALUES (?,?,?,?,?)').run(keyId, req.user.id, String(req.body?.name || 'Tadoo API key').slice(0, 60), hash(token), now()); res.status(201).json({ key: token, id: keyId, warning: 'Store this key securely. It will not be shown again.' }) })
app.delete('/api/keys/:id', auth, (req, res) => { const result = db.prepare('DELETE FROM api_keys WHERE id=? AND user_id=?').run(req.params.id, req.user.id); if (!result.changes) return res.status(404).json({ error: 'API key not found' }); res.status(204).end() })

app.listen(port, () => console.log(`Tadoo API listening on http://localhost:${port}`))
export default app
